// Server-only Firestore access for campaigns, plus the two LLM operations
// ported from app/services/campaign_service.py.
import { db, COLLECTIONS, FieldValue, Timestamp, serializeCampaign } from "../firestore";
import { llmJson } from "./llm";
import { CAMPAIGN_GENERATOR_PROMPT, CAMPAIGN_IMPROVER_PROMPT } from "./prompts";
import { getStrategy } from "./strategy";

// idea      - created by hand
// proposal  - generated by the LLM
// in_review - feedback submitted
// active    - accepted; the planner draws only from these
// rejected / completed - terminal
export const CAMPAIGN_STATUSES = [
  "idea",
  "proposal",
  "in_review",
  "active",
  "rejected",
  "completed",
] as const;

/** Statuses that count as live for dedupe when generating new ideas. */
const OPEN_STATUSES = ["idea", "proposal", "in_review", "active"];

/** How many past feedback entries to send to the improver. */
const FEEDBACK_HISTORY_LIMIT = 10;

function asObject(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

function isDateString(value: unknown): value is string {
  return typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value);
}

export function parseCampaignCreate(
  body: unknown
): { data: Record<string, unknown> } | { error: string } {
  const b = (body ?? {}) as Record<string, unknown>;
  const title = typeof b.title === "string" ? b.title.trim() : "";
  if (!title) return { error: "Title is required." };

  return {
    data: {
      title,
      description: typeof b.description === "string" ? b.description.trim() : null,
      status: "idea",
      strategy: asObject(b.strategy),
      contentPlan: asObject(b.content_plan),
      pacing: "even",
      feedbackHistory: [],
      rejectionReason: null,
      startDate: isDateString(b.start_date) ? b.start_date : null,
      endDate: isDateString(b.end_date) ? b.end_date : null,
    },
  };
}

// Explicit null clears; an absent key is skipped.
export function parseCampaignPatch(
  body: unknown
): { data: Record<string, unknown> } | { error: string } {
  const b = (body ?? {}) as Record<string, unknown>;
  const update: Record<string, unknown> = {};

  if ("title" in b) {
    const title = typeof b.title === "string" ? b.title.trim() : "";
    if (!title) return { error: "Title cannot be empty." };
    update.title = title;
  }
  if ("description" in b) {
    update.description = typeof b.description === "string" ? b.description.trim() : null;
  }
  if ("status" in b) {
    if (
      typeof b.status !== "string" ||
      !(CAMPAIGN_STATUSES as readonly string[]).includes(b.status)
    ) {
      return { error: `Status must be one of: ${CAMPAIGN_STATUSES.join(", ")}.` };
    }
    update.status = b.status;
  }
  if ("strategy" in b) update.strategy = asObject(b.strategy);
  if ("content_plan" in b) update.contentPlan = asObject(b.content_plan);
  if ("pacing" in b) update.pacing = typeof b.pacing === "string" ? b.pacing : "even";

  for (const [apiField, docField] of [
    ["start_date", "startDate"],
    ["end_date", "endDate"],
  ] as const) {
    if (!(apiField in b)) continue;
    if (b[apiField] === null) {
      update[docField] = null;
    } else if (isDateString(b[apiField])) {
      update[docField] = b[apiField];
    } else {
      return { error: `${apiField} must be YYYY-MM-DD or null.` };
    }
  }

  if (Object.keys(update).length === 0) {
    return { error: "No recognised fields to update." };
  }
  return { data: update };
}

export async function listCampaigns(clientId: string, status?: string) {
  const snap = await db()
    .collection(COLLECTIONS.campaigns)
    .where("clientId", "==", clientId)
    .get();

  let rows = snap.docs.map((doc) => serializeCampaign(doc.id, doc.data()));
  if (status) rows = rows.filter((r) => r.status === status);

  // Sorted in memory to avoid a composite index, per house style.
  return rows.sort((a, b) => (b.created_at ?? "").localeCompare(a.created_at ?? ""));
}

export async function getCampaign(clientId: string, campaignId: string) {
  const snap = await db().collection(COLLECTIONS.campaigns).doc(campaignId).get();
  if (!snap.exists) return null;
  const data = snap.data() ?? {};
  // Scope check: a campaign id from another client must read as missing.
  if (data.clientId !== clientId) return null;
  return serializeCampaign(snap.id, data);
}

export async function createCampaign(clientId: string, data: Record<string, unknown>) {
  const ref = db().collection(COLLECTIONS.campaigns).doc();
  await ref.set({
    clientId,
    ...data,
    createdAt: FieldValue.serverTimestamp(),
    updatedAt: FieldValue.serverTimestamp(),
  });
  const snap = await ref.get();
  return serializeCampaign(ref.id, snap.data() ?? {});
}

export async function updateCampaign(campaignId: string, update: Record<string, unknown>) {
  const ref = db().collection(COLLECTIONS.campaigns).doc(campaignId);
  await ref.set({ ...update, updatedAt: FieldValue.serverTimestamp() }, { merge: true });
  const snap = await ref.get();
  return serializeCampaign(ref.id, snap.data() ?? {});
}

export async function deleteCampaign(campaignId: string) {
  await db().collection(COLLECTIONS.campaigns).doc(campaignId).delete();
}

/**
 * Append a feedback entry. Review and improve write different shapes — review
 * has submitted_at, improve has improved_at + changes — so the array is
 * heterogeneous by design and the UI already renders both.
 */
export async function appendFeedback(
  campaignId: string,
  entry: Record<string, unknown>,
  extra: Record<string, unknown> = {}
) {
  const ref = db().collection(COLLECTIONS.campaigns).doc(campaignId);
  await ref.set(
    {
      // serverTimestamp() is illegal inside an array element, so the entry
      // carries its own ISO timestamp.
      feedbackHistory: FieldValue.arrayUnion(entry),
      ...extra,
      updatedAt: FieldValue.serverTimestamp(),
    },
    { merge: true }
  );
  const snap = await ref.get();
  return serializeCampaign(campaignId, snap.data() ?? {});
}

// --- LLM operations ---

export class NoStrategyError extends Error {
  constructor() {
    super("No strategy configured for this client.");
    this.name = "NoStrategyError";
  }
}

/** Port of campaign_service.generate_campaign_ideas (temperature 0.8). */
export async function generateCampaignIdeas(
  clientId: string,
  opts: { prompt?: string; count?: number } = {}
) {
  const strategy = await getStrategy(clientId);
  if (!strategy) throw new NoStrategyError();

  // Dedupe against open campaigns only; rejected and completed ones are
  // deliberately excluded so a good idea can come back later.
  const open = (await listCampaigns(clientId))
    .filter((c) => OPEN_STATUSES.includes(c.status))
    .slice(0, 10);

  const result = await llmJson<{ campaigns?: Record<string, unknown>[] }>({
    systemPrompt: CAMPAIGN_GENERATOR_PROMPT,
    temperature: 0.8,
    payload: {
      strategy: {
        business_name: strategy.business_name,
        icp: strategy.icp,
        voice: strategy.voice,
        positioning: strategy.positioning,
        messaging: strategy.messaging,
        goals: strategy.goals,
      },
      content_quota: strategy.content_quota ?? {},
      existing_campaigns: open.map((c) => c.title),
      count: opts.count ?? 3,
      user_prompt: opts.prompt || "Generate diverse campaign ideas based on the strategy.",
    },
  });

  // Defensive parsing, matching the Python: a missing key yields an empty list
  // rather than an error, and each field falls back to a safe default.
  const ideas = Array.isArray(result.campaigns) ? result.campaigns : [];
  const batch = db().batch();
  const refs = ideas.map((idea) => {
    const ref = db().collection(COLLECTIONS.campaigns).doc();
    batch.set(ref, {
      clientId,
      title: typeof idea.title === "string" ? idea.title : "Untitled Campaign",
      description: typeof idea.description === "string" ? idea.description : "",
      status: "proposal",
      strategy: asObject(idea.strategy),
      contentPlan: asObject(idea.content_plan),
      pacing: "even",
      feedbackHistory: [],
      rejectionReason: null,
      startDate: null,
      endDate: null,
      createdAt: FieldValue.serverTimestamp(),
      updatedAt: FieldValue.serverTimestamp(),
    });
    return ref;
  });
  if (refs.length) await batch.commit();

  const snaps = await Promise.all(refs.map((r) => r.get()));
  return snaps.map((s) => serializeCampaign(s.id, s.data() ?? {}));
}

/** Port of campaign_service.improve_campaign (temperature 0.6). Status unchanged. */
export async function improveCampaign(
  clientId: string,
  campaignId: string,
  feedback: string
) {
  const campaign = await getCampaign(clientId, campaignId);
  if (!campaign) return null;

  const history = campaign.feedback_history ?? [];

  const result = await llmJson<Record<string, unknown>>({
    systemPrompt: CAMPAIGN_IMPROVER_PROMPT,
    temperature: 0.6,
    payload: {
      campaign: {
        title: campaign.title,
        description: campaign.description,
        strategy: campaign.strategy,
        content_plan: campaign.content_plan,
      },
      // Capped: the Python sent the entire unbounded history on every call, so
      // the prompt grew without limit as a campaign was iterated on.
      feedback_history: history.slice(-FEEDBACK_HISTORY_LIMIT),
      new_feedback: feedback,
    },
  });

  // Each field falls back to the current value when the model omits the key.
  const update: Record<string, unknown> = {
    title: typeof result.title === "string" ? result.title : campaign.title,
    description:
      typeof result.description === "string" ? result.description : campaign.description,
    strategy: result.strategy !== undefined ? asObject(result.strategy) : campaign.strategy,
    contentPlan:
      result.content_plan !== undefined ? asObject(result.content_plan) : campaign.content_plan,
  };

  return appendFeedback(
    campaignId,
    {
      feedback,
      improved_at: Timestamp.now().toDate().toISOString(),
      changes: typeof result.changes_made === "string" ? result.changes_made : "",
    },
    update
  );
}
