import { describe, it, expect } from "vitest";
import corpus from "./__fixtures__/corpus.json";
import { readCopy, copyWarnings } from "./copy";
import { ctaWarnings, languageOf, wordsToAvoidOf } from "./brand";
import { languageWarnings } from "./language";
import { humanizeFindings } from "./humanize";
import { pieceWarnings } from "./warnings";

// The checks, run over copy the model actually wrote, and the result written
// down where a diff can find it.
//
// Every other test in this repo asks "does this check fire on the string I
// built to make it fire?". That proves the rule works and says nothing about
// whether it is CALIBRATED — whether a marker list has quietly started firing
// on every piece, whether a threshold change moved anything at all. Those are
// questions about a corpus, and this is the corpus.
//
// The committed report is the artifact. Change THEME_COLLISION_THRESHOLD or
// drop a word from EN_MARKERS, run `npx vitest run -u lib/marketing/corpus`,
// and the diff says in plain English what it did. A change that moves nothing
// across 30 real pieces was not worth making; one that moves everything wants
// looking at before it ships.
//
// What it does NOT measure: the prompts. These fixtures are frozen output, so
// editing a prompt does not move them. That needs live generation, which costs
// money per run, and is deliberately not here.

interface Piece {
  slot_id: string;
  client_id: string;
  type: string;
  channel: string;
  cta: string;
  content: Record<string, unknown>;
}

const PIECES = corpus.pieces as Piece[];
const CLIENTS = corpus.clients as Record<string, Record<string, unknown>>;

/** The eight things that can be wrong, kept apart so the report can attribute. */
const CATEGORIES = [
  "copy",
  "language",
  "cta",
  "leakage",
  "avoided",
  "density",
  "phrases",
  "structure",
] as const;
type Category = (typeof CATEGORIES)[number];

function scoreOf(piece: Piece): { total: number; by: Record<Category, string[]> } {
  const strategy = CLIENTS[piece.client_id] ?? null;
  const copy = readCopy(piece);
  const language = languageOf(strategy);
  const human = humanizeFindings(copy, {
    language,
    wordsToAvoid: wordsToAvoidOf(strategy),
  });

  return {
    // What the operator actually sees in the banner: the capped, ordered list.
    total: pieceWarnings(copy, piece, strategy).length,
    by: {
      copy: copy ? copyWarnings(copy, piece) : [],
      language: languageWarnings(copy, language),
      cta: ctaWarnings(piece.cta, language),
      leakage: human.leakage,
      avoided: human.avoided,
      density: human.density,
      phrases: human.phrases,
      structure: human.structure,
    },
  };
}

function report(): string {
  const scored = PIECES.map((p) => ({ piece: p, score: scoreOf(p) }));
  const lines: string[] = [];

  lines.push("# Corpus report");
  lines.push("");
  lines.push(
    `Captured ${corpus.captured_at} · ${PIECES.length} pieces · ${Object.keys(CLIENTS).length} clients`
  );
  lines.push("");
  lines.push("Generated by `corpus.test.ts`. Re-bless with `npx vitest run -u lib/marketing/corpus`.");
  lines.push("");
  lines.push(
    "Read the totals as a BASELINE, not a verdict. This copy was generated " +
      "before the checks scoring it existed, so a finding here can mean the " +
      "check is right about old output, or that the check is miscalibrated. " +
      "What the file is for is the DIFF: what a change to a threshold, a " +
      "marker list or a rule does to thirty real pieces."
  );
  lines.push("");

  lines.push("## What the banner shows");
  lines.push("");
  const totals = scored.map((s) => s.score.total);
  const clean = totals.filter((t) => t === 0).length;
  lines.push(`- ${clean} of ${PIECES.length} pieces warn about nothing`);
  lines.push(`- ${totals.reduce((a, b) => a + b, 0)} warnings in total`);
  lines.push(`- worst piece: ${Math.max(0, ...totals)} warnings`);
  lines.push("");

  lines.push("## By check");
  lines.push("");
  lines.push("| Check | Pieces | Findings |");
  lines.push("| --- | ---: | ---: |");
  for (const c of CATEGORIES) {
    const hits = scored.filter((s) => s.score.by[c].length > 0).length;
    const count = scored.reduce((n, s) => n + s.score.by[c].length, 0);
    lines.push(`| ${c} | ${hits} | ${count} |`);
  }
  lines.push("");

  lines.push("## By client");
  lines.push("");
  lines.push("| Client | Language | Pieces | Findings |");
  lines.push("| --- | --- | ---: | ---: |");
  for (const clientId of Object.keys(CLIENTS)) {
    const mine = scored.filter((s) => s.piece.client_id === clientId);
    const declared = (CLIENTS[clientId]?.content_strategy as { language?: { name?: string } })
      ?.language?.name;
    const findings = mine.reduce(
      (n, s) => n + CATEGORIES.reduce((m, c) => m + s.score.by[c].length, 0),
      0
    );
    lines.push(
      `| ${clientId} | ${declared ?? "**unset** → English"} | ${mine.length} | ${findings} |`
    );
  }
  lines.push("");

  lines.push("## Every finding");
  lines.push("");
  for (const { piece, score } of scored) {
    // A warning quotes the copy, which carries newlines. One finding is one
    // line here or the bullets break and the diff becomes unreadable.
    const found = CATEGORIES.flatMap((c) =>
      score.by[c].map((w) => `${c}: ${w.replace(/\s+/g, " ").trim()}`)
    );
    lines.push(`### ${piece.slot_id}`);
    lines.push("");
    lines.push(`\`${piece.type}\` on \`${piece.channel}\` · ${found.length} findings`);
    lines.push("");
    if (found.length === 0) lines.push("- (nothing)");
    for (const f of found) lines.push(`- ${f}`);
    lines.push("");
  }

  return lines.join("\n");
}

describe("the corpus", () => {
  it("is big enough to say anything", () => {
    // A report over three pieces is an anecdote. Guard the floor so a capture
    // that silently returned almost nothing does not become the baseline.
    expect(PIECES.length).toBeGreaterThanOrEqual(20);
  });

  it("carries a strategy for every client it holds copy for", () => {
    for (const p of PIECES) expect(CLIENTS[p.client_id], p.client_id).toBeDefined();
  });

  it("reads back as copy, which is what the checks are handed", () => {
    // If readCopy rejects a fixture the report scores it as clean, and a
    // silently empty corpus is worse than no corpus.
    for (const p of PIECES) expect(readCopy(p), p.slot_id).not.toBeNull();
  });
});

describe("the report", () => {
  it("matches the committed baseline", async () => {
    await expect(report()).toMatchFileSnapshot("./__fixtures__/baseline.md");
  });
});
